[package]
name = "smista-cli"
version = { workspace = true }
authors = { workspace = true }
categories = { workspace = true }
edition = { workspace = true }
keywords = { workspace = true }
license = "Elastic-2.0"
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "smista command-line interface."

[[bin]]
name = "smista"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
globset = { workspace = true }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
smista-sdk = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
yaml_serde = { workspace = true }
