[package]
name = "smista-router-client"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "Async Rust client for the smista-router HTTP JSON API."
license = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
readme = "README.md"
rust-version = { workspace = true }
