// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorBody } from "./ApiErrorBody.js";

/**
 * Envelope wrapping the error body under an `error` key.
 */
export type ApiError = { 
/**
 * The structured error payload.
 */
error: ApiErrorBody, };
