// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * The structured payload of an [`ApiError`].
 *
 * `details` carries machine-readable context (such as the offending provider
 * and model) and is omitted when there is none. It must never contain secrets.
 */
export type ApiErrorBody = { 
/**
 * Stable machine-readable error code, for example `missing_provider_credentials`.
 */
code: string, 
/**
 * Human-readable, actionable description of what went wrong.
 */
message: string, 
/**
 * Optional structured context; never carries secrets.
 */
details?: JsonValue, };
