// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The decision made on a pending approval.
 *
 * Each variant serializes to its lowercase name.
 */
export type ApprovalDecision = "approved" | "rejected";
