// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecision } from "./ApprovalDecision.js";

/**
 * A decision for a [`PendingApproval`](super::PendingApproval) with no tool.
 */
export type ApprovalDecisionEntry = { 
/**
 * Identifier of the approval the decision applies to.
 */
approval_id: string, 
/**
 * The decision being submitted.
 */
decision: ApprovalDecision, 
/**
 * Optional human-readable reason for the decision.
 */
reason?: string, };
