// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecision } from "./ApprovalDecision.js";

/**
 * Payload of a [`TraceEventType::Approval`] event.
 */
export type ApprovalPayload = { 
/**
 * Type of the entity the decision applies to (for example `tool_call`).
 */
target_type: string, 
/**
 * Identifier of the entity the decision applies to.
 */
target_id: string, 
/**
 * The decision that was recorded.
 */
decision: ApprovalDecision, 
/**
 * Human-readable reason for the decision, if any.
 */
reason?: string, };
