// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a [`PendingApproval`].
 */
export type ApprovalKind = "remote_disclosure" | "cost_limit" | "plan";
