// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextFile } from "./ContextFile.js";
import type { ContextInstruction } from "./ContextInstruction.js";
import type { Skill } from "./Skill.js";

/**
 * Local content the client supplies because the router has no filesystem.
 *
 * Every file, instruction and skill the task may need from disk travels here.
 * History, memory and the assembled context are not part of this — the router
 * owns them.
 */
export type Attachments = { 
/**
 * Explicit `@path` files included with their content.
 */
files: Array<ContextFile>, 
/**
 * Instruction documents the client read from disk.
 */
instructions: Array<ContextInstruction>, 
/**
 * Skills the user explicitly invoked, with their full `SKILL.md` body.
 *
 * Authoritative: routing rules may match on them by name, and their
 * instructions are added to the model preamble. The router never infers
 * this set from the prompt.
 */
invoked_skills: Array<Skill>, 
/**
 * Skills offered for the serving model to activate by reading them.
 *
 * Same shape as the invoked skills, but distinct by role: they never
 * influence routing, and the model decides whether to apply one. The full
 * instructions travel up front, so an activated skill needs no follow-up
 * fetch.
 */
available_skills: Array<Skill>, };
