// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextFile } from "./ContextFile.js";
import type { ContextInstruction } from "./ContextInstruction.js";
import type { Skill } from "./Skill.js";

/**
 * Local content the client supplies because the router has no filesystem.
 *
 * Every file, instruction and skill the task may need from disk travels here.
 * History, memory and the assembled context are not part of this — the router
 * owns them.
 */
export type Attachments = { 
/**
 * Explicit `@path` files included with their content.
 */
files: Array<ContextFile>, 
/**
 * Instruction documents the client read from disk.
 */
instructions: Array<ContextInstruction>, 
/**
 * Invoked skills, as name plus the `SKILL.md` body.
 */
skills: Array<Skill>, };
