// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `POST /auth/bootstrap`, returned once at user creation.
 *
 * `api_key` is a secret shown only here; the caller must store it securely.
 */
export type BootstrapResponse = { 
/**
 * Identifier of the created user, for example `user:abc123`.
 */
user_id: string, 
/**
 * Long-lived smista API key. Secret; shown only in this response.
 */
api_key: string, };
