// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single model capability, used to report which one a task requires.
 *
 * Each variant serializes to its lowercase snake_case name.
 */
export type Capability = "streaming" | "tools" | "json_output" | "system_prompt" | "images" | "reasoning" | "memory";
