// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence.js";
import type { IntentSource } from "./IntentSource.js";
import type { TaskIntent } from "./TaskIntent.js";

/**
 * The outcome of intent classification for one request.
 *
 * Either the user supplied an explicit intent (see [`IntentSource::Explicit`])
 * or one was inferred deterministically from a matching
 * [`ClassificationRule`] (see [`IntentSource::Inferred`]). For an inferred
 * intent, [`matched_rule`](Self::matched_rule) carries the index of the
 * matching entry in [`ClassificationConfig::rules`] so traces can point back
 * to the configured rule.
 */
export type Classification = { 
/**
 * The detected task intent.
 */
intent: TaskIntent, 
/**
 * Whether the intent was given explicitly by the user or inferred.
 */
source: IntentSource, 
/**
 * Human-readable explanation of why this intent was chosen.
 */
reason: string, 
/**
 * Index of the matched rule in [`ClassificationConfig::rules`], if any.
 *
 * Refers to a [`ClassificationRule`].
 */
matched_rule?: number, 
/**
 * Optional deterministic confidence category for an inferred intent.
 */
confidence?: Confidence, };
