// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskIntent } from "./TaskIntent.js";

/**
 * A single intent-classification rule.
 *
 * A rule maps observable signals in the request to a [`TaskIntent`]. All
 * present conditions must hold for the rule to match:
 *
 * - [`keywords`](Self::keywords) — at least one keyword appears in the prompt.
 * - [`requires_any_context`](Self::requires_any_context) — at least one of the
 *   named context kinds (for example `git_diff` or `pull_request`) is
 *   available for the task.
 *
 * Absent conditions are ignored; a rule with no conditions matches every
 * request.
 *
 * # Examples
 *
 * ```
 * use smista_core::intent::TaskIntent;
 * use smista_core::policy::ClassificationRule;
 *
 * let rule: ClassificationRule = serde_json::from_value(serde_json::json!({
 *     "intent": "review",
 *     "priority": 10,
 *     "keywords": ["review", "audit", "check"],
 *     "requires_any_context": ["git_diff", "pull_request"],
 * }))
 * .unwrap();
 * assert_eq!(rule.intent, TaskIntent::Review);
 * assert_eq!(rule.priority, 10);
 * ```
 */
export type ClassificationRule = { 
/**
 * Intent assigned when the rule matches.
 */
intent: TaskIntent, 
/**
 * Evaluation priority; rules are evaluated in ascending order (lower
 * first). Defaults to `1000` when unset.
 */
priority: number, 
/**
 * Keywords; the rule matches when any appears in the prompt.
 */
keywords: Array<string>, 
/**
 * Required context kinds; the rule matches when any is available.
 */
requires_any_context: Array<string>, };
