// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassificationRule } from "./ClassificationRule.js";
import type { TaskIntent } from "./TaskIntent.js";

/**
 * Configuration for intent classification.
 *
 * Holds the ordered set of [`rules`](Self::rules) used to infer a
 * [`TaskIntent`] from a prompt and its available context kinds, plus the
 * [`default_intent`](Self::default_intent) returned when no rule matches.
 *
 * # Examples
 *
 * ```
 * use smista_core::intent::TaskIntent;
 * use smista_core::policy::ClassificationConfig;
 *
 * let config = ClassificationConfig::default();
 * assert_eq!(config.default_intent, TaskIntent::Chat);
 * assert!(config.rules.is_empty());
 * ```
 */
export type ClassificationConfig = { 
/**
 * Intent used when no rule matches.
 */
default_intent: TaskIntent, 
/**
 * Ordered intent-classification rules.
 */
rules: Array<ClassificationRule>, };
