// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Classification } from "./Classification.js";
import type { ContextOutcome } from "./ContextOutcome.js";
import type { Message } from "./Message.js";
import type { RoutingOutcome } from "./RoutingOutcome.js";
import type { Usage } from "./Usage.js";

/**
 * The payload of a [`completed`](TurnResponse::Completed) turn.
 */
export type CompletedTurn = { 
/**
 * The assistant's reply.
 */
message: Message, 
/**
 * How the task was classified.
 */
classification: Classification, 
/**
 * How the task was routed.
 */
routing: RoutingOutcome, 
/**
 * What context was included and excluded.
 */
context: ContextOutcome, 
/**
 * Token usage and cost for the turn.
 */
usage: Usage, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, };
