// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deterministic confidence category for an inferred intent.
 *
 * This is a coarse signal-strength label, not a probability.
 */
export type Confidence = "low" | "medium" | "high";
