// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to one sealable content record, by its store and id.
 *
 * The textual form is `kind:id`, where `kind` names the content store the
 * record's body lives in. Each variant maps to one of the session-scoped
 * `_content` stores (and the trace payload store) that end-to-end encryption
 * seals.
 */
export type ContentRef = string;
