// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file included as context, with a content hash for cache validation.
 */
export type ContextFile = { 
/**
 * Path of the file.
 */
path: string, 
/**
 * File content.
 */
content: string, 
/**
 * Hash of the content, for example `sha256:...`.
 */
content_hash: string, };
