// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An instruction document the client attached as context.
 */
export type ContextInstruction = { 
/**
 * Where the instruction came from, for example `SMISTA.md`.
 */
source: string, 
/**
 * The instruction content.
 */
content: string, };
