// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of a [`TraceEventType::ContextSelection`] event.
 *
 * Records a reference to the selected or excluded context — its path and kind —
 * never the context body itself.
 */
export type ContextSelectionPayload = { 
/**
 * Path of the referenced context, if it has one.
 */
path?: string, 
/**
 * Kind of context (for example `git_diff` or `file`).
 */
kind: string, 
/**
 * Whether the context was included (`true`) or excluded (`false`).
 */
included: boolean, 
/**
 * Human-readable explanation of the selection.
 */
reason: string, };
