// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a [`ContinueRequest`], as advertised in
 * [`allowed_continuations`](super::TurnResponse).
 */
export type ContinueKind = "tool_results" | "approval_decisions" | "decrypted" | "sealed" | "inject" | "break";
