// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecisionEntry } from "./ApprovalDecisionEntry.js";
import type { ContentRef } from "./ContentRef.js";
import type { EncryptedPayload } from "./EncryptedPayload.js";
import type { ToolResult } from "./ToolResult.js";
import type { UserMessage } from "./UserMessage.js";

/**
 * A single tagged message that advances an in-flight run.
 *
 * Serialized adjacently tagged: `{ "type": <kind>, "data": { … } }`, except the
 * data-less [`Break`](Self::Break), which is just `{ "type": "break" }`.
 */
export type ContinueRequest = { "type": "tool_results", "data": { 
/**
 * One entry per executed call, correlated by `call_id`.
 */
results: Array<ToolResult>, 
/**
 * Sealed forms of router-authored rows (the assistant message, tool
 * arguments) and of the tool results, keyed by [`ContentRef`]. Empty
 * unless the session is end-to-end encrypted.
 */
encrypted?: { [key in ContentRef]?: EncryptedPayload }, } } | { "type": "approval_decisions", "data": { 
/**
 * One entry per pending approval.
 */
decisions: Array<ApprovalDecisionEntry>, 
/**
 * Sealed router-authored rows (for example a plan snapshot), keyed by
 * [`ContentRef`]. Empty unless the session is end-to-end encrypted.
 */
encrypted?: { [key in ContentRef]?: EncryptedPayload }, } } | { "type": "decrypted", "data": { 
/**
 * Opened `to_decrypt` records plus plaintext from same-turn
 * `to_encrypt` records, keyed by [`ContentRef`].
 */
plaintext: { [key in ContentRef]?: string }, 
/**
 * Sealed forms of router-authored rows the turn asked to seal alongside
 * the decrypt (for example the run-input bundle), keyed by
 * [`ContentRef`]. Empty unless the session is end-to-end encrypted.
 */
encrypted?: { [key in ContentRef]?: EncryptedPayload }, } } | { "type": "sealed", "data": { 
/**
 * [`ContentRef`] -> sealed envelope.
 */
encrypted: { [key in ContentRef]?: EncryptedPayload }, } } | { "type": "inject", "data": { 
/**
 * The queued user messages, in order.
 */
messages: Array<UserMessage>, } } | { "type": "break" };
