// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What context the router included and excluded for a task.
 */
export type ContextOutcome = { 
/**
 * Human-readable descriptions of included context.
 */
included: Array<string>, 
/**
 * Human-readable descriptions of excluded context.
 */
excluded: Array<string>, };
