// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file the client attached, with a content hash and whether it is required.
 */
export type ContextFile = { 
/**
 * Path of the file.
 */
path: string, 
/**
 * File content.
 */
content: string, 
/**
 * Hash of the content, for example `sha256:...`.
 */
content_hash: string, 
/**
 * Whether the file is required (referenced or route-driving) and so cannot
 * be dropped, as opposed to discardable supplementary context.
 */
required: boolean, };
