// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecisionEntry } from "./ApprovalDecisionEntry.js";
import type { PlainRecord } from "./PlainRecord.js";
import type { SealedRecord } from "./SealedRecord.js";
import type { ToolResult } from "./ToolResult.js";
import type { UserMessage } from "./UserMessage.js";

/**
 * Bundle that advances an in-flight run after a continuation.
 *
 * Every field defaults to empty, so a bare `{}` is a valid no-op and a bare
 * `{ "interrupt": true }` aborts the in-flight turn with no other input.
 */
export type ContinueRequest = { 
/**
 * Results of tools the client ran, answering an `awaiting_tool` turn.
 */
tool_results: Array<ToolResult>, 
/**
 * Decisions for approvals with no tool to run, answering an
 * `awaiting_approval` turn.
 */
approval_decisions: Array<ApprovalDecisionEntry>, 
/**
 * Records the client decrypted, answering an `awaiting_decrypt` turn.
 */
decrypted: Array<PlainRecord>, 
/**
 * Records the client encrypted, answering an `awaiting_encrypt` turn.
 */
encrypted: Array<SealedRecord>, 
/**
 * User input typed while the run was working, delivered at this boundary.
 */
user_messages: Array<UserMessage>, 
/**
 * Whether to abort the in-flight turn (the Esc path).
 */
interrupt: boolean, };
