// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An estimated cost range in a given currency.
 *
 * `min` and `max` serialize as decimal strings to preserve monetary precision.
 */
export type CostRange = { 
/**
 * Lower bound of the estimate, as a decimal string.
 */
min: string, 
/**
 * Upper bound of the estimate, as a decimal string.
 */
max: string, 
/**
 * ISO 4217 currency code for the bounds.
 */
currency: string, };
