// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";

/**
 * Payload of a [`TraceEventType::Cost`] event.
 */
export type CostPayload = { 
/**
 * Provider that served the task.
 */
provider: Provider, 
/**
 * Model that served the task.
 */
model: string, 
/**
 * Input tokens consumed.
 */
input_tokens: number, 
/**
 * Output tokens produced.
 */
output_tokens: number, 
/**
 * Estimated cost as a decimal string, if known. Never a float.
 */
cost?: string, };
