// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /sessions`. The title is mandatory.
 */
export type CreateSessionRequest = { 
/**
 * Title for the new session.
 */
title: string, };
