// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /sessions`. The title is mandatory.
 *
 * `key_id` opts the session into end-to-end encryption: a session is encrypted
 * when, and only when, a `key_id` is present, naming the fingerprint of the
 * per-session key the client holds. There is no separate `encrypted` flag, so
 * the two can never disagree. The choice is fixed for the life of the session.
 */
export type CreateSessionRequest = { 
/**
 * Title for the new session.
 */
title: string, 
/**
 * Fingerprint of the per-session key; its presence makes the session
 * end-to-end encrypted.
 */
key_id?: string, };
