// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary.js";

/**
 * Response to `POST /sessions`, wrapping the created session.
 */
export type CreateSessionResponse = { 
/**
 * The created session.
 */
session: SessionSummary, };
