// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelReference } from "./ModelReference.js";

/**
 * The default route, applied when no routing rule matches.
 *
 * Mirrors the `[routing.default]` table.
 *
 * # Examples
 *
 * ```
 * use smista_core::policy::DefaultRoute;
 *
 * let route: DefaultRoute = serde_json::from_value(serde_json::json!({
 *     "model": "openai/gpt-5.5-mini",
 *     "fallbacks": ["ollama/qwen2.5-coder"],
 * }))
 * .unwrap();
 * assert_eq!(route.model.to_string(), "openai/gpt-5.5-mini");
 * ```
 */
export type DefaultRoute = { 
/**
 * Model used when no rule matches.
 */
model: ModelReference, 
/**
 * Models tried, in order, when the default model is unavailable.
 */
fallbacks: Array<ModelReference>, };
