// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `DELETE /sessions/{id}`, confirming deletion.
 */
export type DeleteSessionResponse = { 
/**
 * Whether the session was deleted.
 */
deleted: boolean, };
