// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The reasoning effort a model should spend on a routed task.
 *
 * Declared per routing rule and passed through to the model as its effort
 * setting. Each variant serializes to its lowercase name. The default is
 * [`Effort::Medium`].
 */
export type Effort = "low" | "medium" | "high" | "xhigh";
