// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The sealed wire form of one content payload: an AEAD ciphertext envelope.
 *
 * Self-describing — it names the algorithm and the key that sealed it, and
 * carries the one-time nonce and the ciphertext (including its authentication
 * tag) — and never carries the key itself. It mirrors the envelope storage
 * persists but is a distinct serialization-first type; the router converts
 * between the two when it persists or returns content.
 */
export type EncryptedPayload = { 
/**
 * Envelope schema version, so the format can evolve.
 */
version: number, 
/**
 * AEAD algorithm identifier, for example `xchacha20poly1305`.
 */
algorithm: string, 
/**
 * Fingerprint of the per-session key that sealed this payload.
 */
key_id: string, 
/**
 * Base64-encoded one-time nonce used for this payload.
 */
nonce: string, 
/**
 * Base64-encoded ciphertext, including the AEAD authentication tag.
 */
ciphertext: string, };
