// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode.js";

/**
 * Tool permission modes for a task.
 */
export type ExecutePermissions = { 
/**
 * Permission for reading files.
 */
file_read: PermissionMode, 
/**
 * Permission for writing files.
 */
file_write: PermissionMode, 
/**
 * Permission for running shell commands.
 */
shell: PermissionMode, 
/**
 * Permission for network access.
 */
network: PermissionMode, };
