// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachments } from "./Attachments.js";
import type { EncryptedPayload } from "./EncryptedPayload.js";
import type { ExecutePolicy } from "./ExecutePolicy.js";
import type { LocalPreferences } from "./LocalPreferences.js";
import type { ProviderCredentialInfo } from "./ProviderCredentialInfo.js";
import type { TaskInput } from "./TaskInput.js";
import type { Workspace } from "./Workspace.js";

/**
 * Full input to executing, streaming, or previewing a task.
 */
export type ExecuteRequest = { 
/**
 * What the user is asking for.
 */
input: TaskInput, 
/**
 * Snapshot of the workspace the task runs against.
 */
workspace: Workspace, 
/**
 * Classification, routing, permission and privacy policy snapshot.
 */
policy: ExecutePolicy, 
/**
 * Client-side execution preferences.
 */
local_preferences: LocalPreferences, 
/**
 * Providers available for this request and their credential status.
 */
providers: Array<ProviderCredentialInfo>, 
/**
 * Local content the router cannot read for itself.
 */
attachments: Attachments, 
/**
 * For an encrypted session, the sealed form of the user prompt, persisted
 * as the user message; the plaintext in `input.text` is what calls the
 * model. Absent for a plaintext session.
 */
input_ciphertext?: EncryptedPayload, };
