// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal status of a task execution.
 *
 * Each variant serializes to its snake_case name.
 */
export type ExecutionStatus = "completed" | "pending_approval";
