// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextOutcome } from "./ContextOutcome.js";
import type { ExecutionStatus } from "./ExecutionStatus.js";
import type { Message } from "./Message.js";
import type { RoutingOutcome } from "./RoutingOutcome.js";
import type { Usage } from "./Usage.js";

/**
 * Outcome of executing a task.
 *
 * `message` is the assistant's reply on completion; it may be absent when the
 * task is awaiting an approval instead.
 */
export type ExecuteResponse = { 
/**
 * Terminal status of the execution.
 */
status: ExecutionStatus, 
/**
 * The assistant's reply, when the task produced one.
 */
message?: Message, 
/**
 * How the task was routed.
 */
routing: RoutingOutcome, 
/**
 * What context was included and excluded.
 */
context: ContextOutcome, 
/**
 * Token usage and cost for the execution.
 */
usage: Usage, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, };
