// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassificationConfig } from "./ClassificationConfig.js";
import type { PrivacyPolicy } from "./PrivacyPolicy.js";
import type { RoutingPolicy } from "./RoutingPolicy.js";
import type { ToolsConfig } from "./ToolsConfig.js";

/**
 * The deterministic policy snapshot the client sends with a task.
 *
 * `version` is the schema version of the snapshot; `source` records how it was
 * assembled (for example `merged`). The `classification`, `routing`, `tools`
 * and `privacy` blocks are the canonical [`crate::policy`] types — the same
 * vocabulary the router evaluates and the CLI loads from `config.toml`.
 */
export type ExecutePolicy = { 
/**
 * Schema version of the policy snapshot.
 */
version: number, 
/**
 * How the snapshot was assembled, for example `merged`.
 */
source: string, 
/**
 * Intent-classification rules and the default intent.
 */
classification: ClassificationConfig, 
/**
 * Routing rules and default route.
 */
routing: RoutingPolicy, 
/**
 * Tool permission modes, keyed by tool name.
 */
tools: ToolsConfig, 
/**
 * Privacy constraints on the context sent to models.
 */
privacy: PrivacyPolicy, };
