// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Privacy constraints on the context sent to models.
 */
export type ExecutePrivacy = { 
/**
 * Glob patterns whose contents must not be sent to remote models.
 */
restricted_paths: Array<string>, 
/**
 * Whether including restricted context in a remote request needs approval.
 */
remote_model_requires_approval_for_restricted_context: boolean, };
