// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutePermissions } from "./ExecutePermissions.js";
import type { ExecutePrivacy } from "./ExecutePrivacy.js";
import type { ExecuteRoutingPolicy } from "./ExecuteRoutingPolicy.js";

/**
 * The deterministic policy snapshot the client sends with a task.
 *
 * `version` is the schema version of the snapshot; `source` records how it was
 * assembled (for example `merged`).
 */
export type ExecutePolicy = { 
/**
 * Schema version of the policy snapshot.
 */
version: number, 
/**
 * How the snapshot was assembled, for example `merged`.
 */
source: string, 
/**
 * Routing rules, default model and fallbacks.
 */
routing: ExecuteRoutingPolicy, 
/**
 * Tool permission modes.
 */
permissions: ExecutePermissions, 
/**
 * Privacy constraints on context.
 */
privacy: ExecutePrivacy, };
