// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteContext } from "./ExecuteContext.js";
import type { ExecutePolicy } from "./ExecutePolicy.js";
import type { LocalPreferences } from "./LocalPreferences.js";
import type { ProviderCredentialInfo } from "./ProviderCredentialInfo.js";
import type { TaskInput } from "./TaskInput.js";
import type { Workspace } from "./Workspace.js";

/**
 * Full input to executing, streaming, or previewing a task.
 */
export type ExecuteRequest = { 
/**
 * What the user is asking for.
 */
input: TaskInput, 
/**
 * Snapshot of the workspace the task runs against.
 */
workspace: Workspace, 
/**
 * Routing, permission and privacy policy snapshot.
 */
policy: ExecutePolicy, 
/**
 * Client-side execution preferences.
 */
local_preferences: LocalPreferences, 
/**
 * Providers available for this request and their credential status.
 */
providers: Array<ProviderCredentialInfo>, 
/**
 * The assembled context for the task.
 */
context: ExecuteContext, };
