// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelReference } from "./ModelReference.js";
import type { RuleMatch } from "./RuleMatch.js";

/**
 * A single routing rule: match criteria and the model to use.
 */
export type ExecuteRoutingRule = { 
/**
 * Criteria that select this rule.
 */
match: RuleMatch, 
/**
 * Model to use when the rule matches.
 */
use: ModelReference, };
