// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteRoutingRule } from "./ExecuteRoutingRule.js";
import type { ModelReference } from "./ModelReference.js";

/**
 * Routing portion of the policy snapshot.
 *
 * `fallbacks` maps a primary model to the ordered models to try if it is
 * unavailable.
 */
export type ExecuteRoutingPolicy = { 
/**
 * Model used when no rule matches.
 */
default_model: ModelReference, 
/**
 * Ordered routing rules.
 */
rules: Array<ExecuteRoutingRule>, 
/**
 * Per-model ordered fallbacks, keyed by the primary model.
 */
fallbacks: { [key in ModelReference]: Array<ModelReference> }, };
