// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextFile } from "./ContextFile.js";
import type { ContextInstruction } from "./ContextInstruction.js";
import type { Message } from "./Message.js";
import type { Skill } from "./Skill.js";

/**
 * The assembled context for a task.
 */
export type ExecuteContext = { 
/**
 * Relevant prior conversation messages.
 */
messages: Array<Message>, 
/**
 * Files included as context.
 */
files: Array<ContextFile>, 
/**
 * Instruction documents included as context.
 */
instructions: Array<ContextInstruction>, 
/**
 * Skills made available to the task.
 */
skills: Array<Skill>, 
/**
 * Prompt template applied to the input, if any.
 */
prompt_template?: string, };
