// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionDetail } from "./SessionDetail.js";

/**
 * Response to `GET /sessions/{id}`, wrapping the full session.
 */
export type GetSessionResponse = { 
/**
 * The fetched session.
 */
session: SessionDetail, };
