// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origin of the intent attached to a request.
 */
export type IntentSource = "explicit" | "inferred";
