// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDescriptor } from "./ModelDescriptor.js";
import type { UnavailableProvider } from "./UnavailableProvider.js";

/**
 * Response to `GET /llm/models`.
 */
export type ListModelsResponse = { 
/**
 * Available models across providers.
 */
models: Array<ModelDescriptor>, 
/**
 * Providers omitted from `models` because listing their models failed,
 * each with the reason it dropped out.
 *
 * The router queries every configured provider when listing models. A
 * provider that cannot be listed — most often because its credentials are
 * missing or were rejected — is left out of `models` and reported here, so
 * a caller can tell an incomplete result from a genuinely empty one and act
 * on the cause. Empty when every configured provider was listed.
 */
unavailable: Array<UnavailableProvider>, };
