// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary.js";

/**
 * Response to `GET /sessions`, wrapping list of sessions.
 */
export type ListSessionsResponse = { 
/**
 * The fetched sessions.
 */
sessions: Array<SessionSummary>, };
