// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInfo } from "./ModelInfo.js";

/**
 * Response to `GET /llm/models`.
 */
export type ListModelsResponse = { 
/**
 * Available models across providers.
 */
models: Array<ModelInfo>, };
