// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderDescriptor } from "./ProviderDescriptor.js";

/**
 * Response to `GET /llm/providers`.
 */
export type ListProvidersResponse = { 
/**
 * Configured and available providers.
 */
providers: Array<ProviderDescriptor>, };
