// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client-side execution preferences.
 */
export type LocalPreferences = { 
/**
 * Apply edits automatically without confirmation.
 */
auto_apply: boolean, 
/**
 * Restrict routing to local models only.
 */
local_only: boolean, 
/**
 * Forbid any network access for this request.
 */
no_network: boolean, };
