// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode.js";

/**
 * Privacy constraints for local models.
 *
 * The effective [`mode`](Self::mode) defaults to [`PermissionMode::Allow`] when
 * unset: local models may receive context without prompting.
 */
export type LocalPrivacy = { 
/**
 * How sending context to local models is mediated, if set.
 */
mode?: PermissionMode, };
