// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `GET /auth/me`, identifying the authenticated user.
 *
 * Carries only the caller's user ID; it lists no sessions and exposes no
 * secret values. To enumerate sessions, use `GET /sessions` instead.
 */
export type MeResponse = { 
/**
 * The authenticated user's unique identifier.
 */
user_id: string, };
