// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary.js";

/**
 * Response to `GET /auth/me`, listing the authenticated user's sessions.
 */
export type MeResponse = { 
/**
 * Summaries of the user's sessions.
 */
sessions: Array<SessionSummary>, };
