// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The role an author plays in a conversation.
 *
 * Each variant serializes to its lowercase name.
 */
export type MessageRole = "system" | "user" | "assistant" | "tool";
