// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageRole } from "./MessageRole.js";
import type { Provider } from "./Provider.js";

/**
 * A single message in a conversation.
 *
 * `provider` and `model` identify which model produced an assistant turn; they
 * are `None` for user, system and tool messages, and may be `None` for an
 * assistant turn whose origin is unknown.
 */
export type Message = { 
/**
 * The role of the message's author.
 */
role: MessageRole, 
/**
 * The textual content of the message.
 */
content: string, 
/**
 * Provider that produced the message, if applicable.
 */
provider?: Provider, 
/**
 * Model that produced the message, if applicable.
 */
model?: string, };
