// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedPayload } from "./EncryptedPayload.js";

/**
 * A session message's content, in clear or sealed.
 *
 * A non-encrypted session yields [`Plaintext`](Self::Plaintext) with the
 * message text. An end-to-end encrypted session yields
 * [`Encrypted`](Self::Encrypted) with the sealed [`EncryptedPayload`] envelope;
 * the router holds no key, so only a client holding the session key can open it
 * back into the message text. This mirrors
 * [`TraceEventPayload`](crate::trace::TraceEventPayload) for message bodies.
 */
export type MessageContent = { "plaintext": string } | { "encrypted": EncryptedPayload };
