// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageRole } from "./MessageRole.js";
import type { Provider } from "./Provider.js";

/**
 * Payload of a [`TraceEventType::Message`] event.
 */
export type MessagePayload = { 
/**
 * Role of the recorded message.
 */
role: MessageRole, 
/**
 * Provider that served the message.
 */
provider: Provider, 
/**
 * Model that served the message.
 */
model: string, };
