// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Sampling and generation parameters for a model invocation.
 *
 * The typed fields are omitted from serialization when unset. Any keys not
 * matching a typed field are collected into [`Self::extra`] and re-emitted as
 * they were, so provider-specific options pass through untouched.
 */
export type ModelParameters = { 
/**
 * Sampling temperature.
 */
temperature: number | null, 
/**
 * Nucleus sampling probability mass.
 */
top_p: number | null, 
/**
 * Maximum number of tokens to generate.
 */
max_tokens: number | null, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
