// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a model is authenticated.
 *
 * Each variant serializes to its snake_case name; [`Self::Custom`] carries the
 * scheme name as its payload (e.g. `{"custom": "aws-sigv4"}`).
 */
export type ModelAuthRequirement = "none" | "api_key" | "optional_api_key" | { "custom": string };
