// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAuthRequirement } from "./ModelAuthRequirement.js";
import type { ModelCapabilities } from "./ModelCapabilities.js";
import type { ModelParameters } from "./ModelParameters.js";
import type { Provider } from "./Provider.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * A complete description of a model offered by a provider.
 *
 * This is also the shape returned for each model by `GET /llm/models`.
 */
export type ModelDescriptor = { 
/**
 * Provider that offers the model.
 */
provider: Provider, 
/**
 * Model name, as defined by the provider.
 */
model: string, 
/**
 * Human-friendly name, if different from `model`.
 */
display_name: string | null, 
/**
 * Whether the model runs locally (no network call).
 */
local: boolean, 
/**
 * How the model is authenticated.
 */
auth: ModelAuthRequirement, 
/**
 * What the model can do.
 */
capabilities: ModelCapabilities, 
/**
 * Maximum number of context tokens the model accepts.
 */
max_context_tokens: number, 
/**
 * Maximum number of tokens the model emits, if bounded.
 */
max_output_tokens: number | null, 
/**
 * Input price per million tokens, serialized as a string for exact precision.
 */
input_cost_per_million_tokens?: string, 
/**
 * Output price per million tokens, serialized as a string for exact precision.
 */
output_cost_per_million_tokens?: string, 
/**
 * Default generation parameters applied when none are supplied.
 */
default_parameters: ModelParameters, 
/**
 * Provider-specific options, preserved verbatim.
 */
provider_options?: JsonValue, };
