// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";

/**
 * Flat description of a model in the public catalog.
 *
 * Capability flags are reported as flat `supports_*` booleans.
 * `supports_json_output` is omitted for models that do not report it.
 */
export type ModelInfo = { 
/**
 * Provider that offers the model.
 */
provider: Provider, 
/**
 * Model name.
 */
model: string, 
/**
 * Whether the model runs locally.
 */
local: boolean, 
/**
 * Whether the model requires an API key.
 */
requires_api_key: boolean, 
/**
 * Whether the model can stream its response.
 */
supports_streaming: boolean, 
/**
 * Whether the model can call tools.
 */
supports_tools: boolean, 
/**
 * Whether the model can be constrained to emit JSON, when reported.
 */
supports_json_output?: boolean, 
/**
 * Maximum number of context tokens the model accepts.
 */
max_context_tokens: number, };
