// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to a specific model offered by a provider.
 *
 * The textual form is `provider/model`, e.g. `anthropic/claude-sonnet`.
 */
export type ModelReference = string;
