// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability.js";
import type { Provider } from "./Provider.js";

/**
 * Flat description of a model in the public catalog.
 *
 * The capabilities a model supports are reported as a list of
 * [`Capability`] values; a capability absent from the list is not supported.
 */
export type ModelInfo = { 
/**
 * Provider that offers the model.
 */
provider: Provider, 
/**
 * Model name.
 */
model: string, 
/**
 * Whether the model runs locally.
 */
local: boolean, 
/**
 * Whether the model requires an API key.
 */
requires_api_key: boolean, 
/**
 * The capabilities the model supports.
 */
capabilities: Array<Capability>, 
/**
 * Maximum number of context tokens the model accepts.
 */
max_context_tokens: number, };
