// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The capabilities a model exposes.
 *
 * Every flag defaults to `false`, so a [`Default`] value advertises no
 * capabilities — a conservative starting point a descriptor builds upon.
 */
export type ModelCapabilities = { 
/**
 * The model can stream its response incrementally.
 */
streaming: boolean, 
/**
 * The model can call tools.
 */
tools: boolean, 
/**
 * The model can be constrained to emit JSON.
 */
json_output: boolean, 
/**
 * The model honors a separate system prompt.
 */
system_prompt: boolean, 
/**
 * The model accepts image inputs.
 */
images: boolean, 
/**
 * The model performs explicit reasoning.
 */
reasoning: boolean, 
/**
 * The model can drive the memory tool to record and update memory.
 *
 * Satisfied by tool calling, or — on providers that offer it, such as
 * OpenAI structured outputs — by a constrained-output equivalent. The
 * router gates memory orchestration on this flag.
 */
memory: boolean, };
