// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalPayload } from "./ApprovalPayload.js";
import type { Classification } from "./Classification.js";
import type { ContextSelectionPayload } from "./ContextSelectionPayload.js";
import type { CostPayload } from "./CostPayload.js";
import type { MessagePayload } from "./MessagePayload.js";
import type { RoutingDecisionPayload } from "./RoutingDecisionPayload.js";
import type { ToolCallPayload } from "./ToolCallPayload.js";

/**
 * The decrypted payload of a [`TraceEvent`], tagged by event kind.
 *
 * Serialized internally tagged under `type` (for example
 * `{ "type": "message", "role": "user", … }`), so it deserializes on its own
 * once a sealed payload has been opened. Its variant always matches the
 * event's [`TraceEventType`].
 */
export type Payload = { "type": "message" } & MessagePayload | { "type": "classification" } & Classification | { "type": "routing_decision" } & RoutingDecisionPayload | { "type": "context_selection" } & ContextSelectionPayload | { "type": "tool_call" } & ToolCallPayload | { "type": "approval" } & ApprovalPayload | { "type": "cost" } & CostPayload;
