// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalKind } from "./ApprovalKind.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * A decision the router needs that has no tool to execute.
 *
 * Raised for disclosures and limits — for example sending context to a remote
 * model under an `ask` privacy mode, or confirming a cost ceiling. The
 * `detail` shape depends on `kind`.
 */
export type PendingApproval = { 
/**
 * Identifier the approval decision refers to.
 */
approval_id: string, 
/**
 * What kind of decision is being asked for.
 */
kind: ApprovalKind, 
/**
 * Machine-readable context for the decision; its shape depends on `kind`.
 */
detail: JsonValue, };
