// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an action is mediated: allowed outright, gated on approval, or blocked.
 *
 * Used by both tool permissions and privacy (remote/local) policies. Variants
 * serialize to their lowercase name. The ordering `Allow < Ask < Deny` reflects
 * increasing strictness, so the stricter of two modes is the greater one — the
 * layered merge relies on this to ensure a higher layer can only tighten, never
 * weaken, a mode.
 *
 * # Examples
 *
 * ```
 * use smista_core::policy::PermissionMode;
 *
 * assert!(PermissionMode::Deny > PermissionMode::Ask);
 * assert_eq!(PermissionMode::Ask.max(PermissionMode::Allow), PermissionMode::Ask);
 * ```
 */
export type PermissionMode = "allow" | "ask" | "deny";
