// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A storage record paired with its cleartext.
 *
 * The router sends these in an `awaiting_encrypt` turn (content to seal); the
 * client returns them in the `/continue` bundle after opening the records of
 * an `awaiting_decrypt` turn. Correlated by `record_id`.
 */
export type PlainRecord = { 
/**
 * Identifier of the storage record the cleartext belongs to.
 */
record_id: string, 
/**
 * The cleartext payload.
 */
plaintext: string, };
