// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Classification } from "./Classification.js";
import type { CostRange } from "./CostRange.js";
import type { RequiredPermission } from "./RequiredPermission.js";
import type { RoutingDecision } from "./RoutingDecision.js";

/**
 * The predicted routing of a task, without calling the model.
 */
export type PreviewResponse = { 
/**
 * How the task would be classified.
 */
classification: Classification, 
/**
 * Complete routing decision the router would apply.
 */
routing: RoutingDecision, 
/**
 * Human-readable descriptions of context that would be included.
 */
included_context: Array<string>, 
/**
 * Human-readable descriptions of context that would be excluded.
 */
excluded_context: Array<string>, 
/**
 * Estimated cost range for the task.
 */
estimated_cost: CostRange, 
/**
 * Permissions the task would require.
 */
required_permissions: Array<RequiredPermission>, };
