// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostRange } from "./CostRange.js";
import type { Provider } from "./Provider.js";
import type { RequiredPermission } from "./RequiredPermission.js";
import type { TaskIntent } from "./TaskIntent.js";

/**
 * The predicted routing of a task, without calling the model.
 */
export type PreviewResponse = { 
/**
 * Task type that would be detected.
 */
task_type: TaskIntent, 
/**
 * Provider that would serve the task.
 */
provider: Provider, 
/**
 * Model that would serve the task.
 */
model: string, 
/**
 * Description of the routing rule that would match, if any.
 */
matched_rule?: string, 
/**
 * Human-readable descriptions of context that would be included.
 */
included_context: Array<string>, 
/**
 * Human-readable descriptions of context that would be excluded.
 */
excluded_context: Array<string>, 
/**
 * Estimated cost range for the task.
 */
estimated_cost: CostRange, 
/**
 * Permissions the task would require.
 */
required_permissions: Array<RequiredPermission>, };
