// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalPrivacy } from "./LocalPrivacy.js";
import type { RemotePrivacy } from "./RemotePrivacy.js";

/**
 * Privacy policy controlling what context may reach which model classes.
 *
 * Mirrors the `[privacy]` configuration: top-level `restricted_paths`, plus a
 * [`remote`](Self::remote) and [`local`](Self::local) sub-policy. These are
 * **safety-critical**: a higher *preference* layer must never silently weaken
 * them, so the CLI merge unions path lists and only lets preference layers
 * tighten the modes (see `smista-cli`'s `config::layers`).
 *
 * Paths are glob patterns kept verbatim; the matcher owns interpretation.
 *
 * # Examples
 *
 * ```
 * use smista_core::policy::{PermissionMode, PrivacyPolicy};
 *
 * let policy: PrivacyPolicy = serde_json::from_value(serde_json::json!({
 *     "restricted_paths": [".env", "secrets/**"],
 *     "remote": { "mode": "ask", "blocked_paths": [".env"] },
 *     "local": { "mode": "allow" },
 * }))
 * .unwrap();
 * assert_eq!(policy.remote.mode(), PermissionMode::Ask);
 * assert_eq!(policy.local.mode(), PermissionMode::Allow);
 * ```
 */
export type PrivacyPolicy = { 
/**
 * Paths treated as sensitive across all model classes.
 */
restricted_paths: Array<string>, 
/**
 * Constraints applied when sending context to remote providers.
 */
remote: RemotePrivacy, 
/**
 * Constraints applied when sending context to local models.
 */
local: LocalPrivacy, };
