// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model offered by a provider and whether its credential is available.
 */
export type ProviderModelInfo = { 
/**
 * Model name.
 */
model: string, 
/**
 * Whether the model requires an API key.
 */
requires_api_key: boolean, 
/**
 * Whether a credential for the model is available to the request.
 */
credential_available: boolean, };
