// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The identifier of a provider, used for configuration and routing.
 *
 * Each variant serializes to its lowercase name.
 */
export type Provider = "anthropic" | "openai" | "ollama";
