// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";

/**
 * A provider together with its runtime configuration state.
 *
 * This is the shape returned by `GET /llm/providers`: it pairs a provider's
 * identity and display name with whether usable credentials (or a base URL,
 * for local providers) are currently configured.
 */
export type ProviderDescriptor = { 
/**
 * The provider this descriptor refers to.
 */
id: Provider, 
/**
 * Human-friendly name shown to users.
 */
display_name: string, 
/**
 * Whether credentials or a base URL are configured for the provider.
 */
configured: boolean, };
