// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of a normalized [`ProviderError`].
 *
 * Each variant captures a category of failure that the router and API layer
 * can reason about independently of the provider-specific HTTP status or
 * SDK error code that produced it. The categories follow the smista.ai
 * specification (Model interfaces → Error handling).
 */
export type ProviderErrorCategory = "authentication" | "context_length" | "invalid_configuration" | "invalid_credentials" | "invalid_request" | "missing_credentials" | "model_not_found" | "provider_unavailable" | "rate_limit" | "storage" | "timeout" | "unknown" | "unsupported_capability";
