// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";

/**
 * A provider that is available for routing.
 *
 * This is the shape returned by `GET /llm/providers`, which lists only the
 * providers that are currently available — those configured with usable
 * credentials (or a base URL, for local providers). A provider that is not
 * available is omitted from the listing entirely, so this descriptor carries
 * no availability flag.
 */
export type ProviderDescriptor = { 
/**
 * The provider this descriptor refers to.
 */
id: Provider, 
/**
 * Human-friendly name shown to users.
 */
display_name: string, 
/**
 * Whether the provider serves its models locally, with no request leaving
 * the host or network.
 *
 * This is the provider-level source of truth for locality: every model the
 * provider offers inherits it, so a provider can never report itself local
 * while a model it advertises routes to the cloud. The router uses it as a
 * routing discriminant to keep sensitive work on local models.
 */
local: boolean, };
