// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";
import type { ProviderModelInfo } from "./ProviderModelInfo.js";

/**
 * A provider available to the request and the credential status of its models.
 */
export type ProviderCredentialInfo = { 
/**
 * Provider identifier.
 */
id: Provider, 
/**
 * Models offered by the provider and their credential status.
 */
models: Array<ProviderModelInfo>, };
