// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode.js";

/**
 * Privacy constraints for remote providers.
 *
 * The effective [`mode`](Self::mode) defaults to [`PermissionMode::Ask`] when
 * unset: disclosing context to a remote provider requires approval unless
 * explicitly allowed.
 */
export type RemotePrivacy = { 
/**
 * How sending context to remote providers is mediated, if set.
 */
mode?: PermissionMode, 
/**
 * Paths that must never be sent to remote providers.
 */
blocked_paths: Array<string>, };
