// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode.js";

/**
 * A permission the task requires and the mode that would apply.
 */
export type RequiredPermission = { 
/**
 * Name of the permission, for example `write_files`.
 */
permission: string, 
/**
 * Mode that would apply to the permission.
 */
mode: PermissionMode, };
