// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";

/**
 * Payload of a [`TraceEventType::RoutingDecision`] event.
 */
export type RoutingDecisionPayload = { 
/**
 * Provider that was selected.
 */
provider: Provider, 
/**
 * Model that was selected.
 */
model: string, 
/**
 * Routing rule that matched, if any.
 */
matched_rule?: string, 
/**
 * Whether a fallback route was used.
 */
fallback_used: boolean, 
/**
 * Whether a per-request override was used.
 */
override_used: boolean, 
/**
 * Human-readable explanation of the decision.
 */
reason: string, };
