// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";
import type { TaskIntent } from "./TaskIntent.js";

/**
 * The complete deterministic routing decision for one task.
 */
export type RoutingDecision = { 
/**
 * Task intent that drove routing.
 */
intent: TaskIntent, 
/**
 * Provider selected to serve the task.
 */
provider: Provider, 
/**
 * Model selected to serve the task.
 */
model: string, 
/**
 * Name of the routing rule that matched, if any.
 */
matched_rule?: string, 
/**
 * Whether a fallback model, rather than the primary, was selected.
 */
fallback_used: boolean, 
/**
 * Whether an explicit model override was selected.
 */
override_used: boolean, 
/**
 * Human-readable explanation of why the route was selected.
 */
reason: string, };
