// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";
import type { TaskIntent } from "./TaskIntent.js";

/**
 * How a task was routed to a model.
 */
export type RoutingOutcome = { 
/**
 * Detected task type that drove routing.
 */
task_type: TaskIntent, 
/**
 * Provider that served the task.
 */
provider: Provider, 
/**
 * Model that served the task.
 */
model: string, 
/**
 * Description of the routing rule that matched, if any.
 */
matched_rule?: string, 
/**
 * Whether a fallback model was used.
 */
fallback_used: boolean, 
/**
 * Whether an explicit model override was used.
 */
override_used: boolean, };
