// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort.js";
import type { ModelCapabilities } from "./ModelCapabilities.js";
import type { ModelReference } from "./ModelReference.js";
import type { TaskIntent } from "./TaskIntent.js";
import type { ToolsConfig } from "./ToolsConfig.js";

/**
 * A single deterministic routing rule.
 *
 * A rule selects [`model`](Self::model) (with optional per-rule
 * [`fallbacks`](Self::fallbacks)) when all of its present match conditions
 * hold. Matching is LLM-free. The match conditions are flat and all optional:
 *
 * - [`intent`](Self::intent): the classified task intent.
 * - [`paths`](Self::paths): file-path globs; a rule with paths matches when a
 *   relevant path matches any glob.
 *
 * A rule with no conditions matches everything (useful as a low-priority
 * catch-all). Rules are evaluated in ascending [`priority`](Self::priority)
 * order; the first match wins.
 *
 * When [`local_only`](Self::local_only) is set, a matched rule must not fall
 * back to remote models — its fallback chain is restricted to local models.
 *
 * A matched rule also declares the [`effort`](Self::effort) the model should
 * spend on the task, defaulting to [`Effort::Medium`].
 *
 * # Examples
 *
 * ```
 * use smista_core::effort::Effort;
 * use smista_core::policy::RoutingRule;
 *
 * let rule: RoutingRule = serde_json::from_value(serde_json::json!({
 *     "name": "auth code uses Claude",
 *     "priority": 30,
 *     "effort": "high",
 *     "intent": "edit",
 *     "paths": ["src/auth/**"],
 *     "model": "anthropic/claude-sonnet",
 *     "fallbacks": ["openai/gpt-5.5-thinking"],
 * }))
 * .unwrap();
 * assert_eq!(rule.name, "auth code uses Claude");
 * assert_eq!(rule.priority, 30);
 * assert_eq!(rule.effort, Effort::High);
 * assert_eq!(rule.model.model, "claude-sonnet");
 * assert_eq!(rule.paths, vec!["src/auth/**".to_string()]);
 * ```
 */
export type RoutingRule = { 
/**
 * Human-readable rule name.
 */
name: string, 
/**
 * Evaluation priority; rules are evaluated in ascending order (lower
 * first). Defaults to `1000` when unset.
 */
priority: number, 
/**
 * Reasoning effort the model should spend on a matched task. Defaults to
 * [`Effort::Medium`] when unset.
 */
effort: Effort, 
/**
 * Required task intent, if any.
 */
intent: TaskIntent | null, 
/**
 * File-path globs; when non-empty, a relevant path must match one of them.
 */
paths: Array<string>, 
/**
 * When set, a matched rule must not fall back to remote models; its
 * fallback chain is restricted to local models.
 */
local_only: boolean, 
/**
 * Capability gate: when set, the matched model must satisfy every
 * capability flagged `true` here.
 */
requires_capabilities?: ModelCapabilities, 
/**
 * Model selected when the rule matches. Using syntax supported by [`ModelReference`] (e.g. `"ollama/llama3"`).
 */
model: ModelReference, 
/**
 * Models tried, in order, when the selected model is unavailable. Subject
 * to [`local_only`](Self::local_only).
 */
fallbacks: Array<ModelReference>, 
/**
 * Tool permissions the matched route requires.
 *
 * Merged over project defaults via [`ToolsConfig::narrow`].
 */
required_permissions: ToolsConfig, 
/**
 * Per-task cost ceiling for the matched route, in account currency.
 *
 * Serialized as a string for exact precision.
 */
cost_limit?: string, };
