// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultRoute } from "./DefaultRoute.js";
import type { RoutingRule } from "./RoutingRule.js";

/**
 * The routing policy: a set of rules plus a default route.
 *
 * Rules are evaluated in ascending priority order; the first match wins. When
 * no rule matches, the [`default`](Self::default) route is used. A complete
 * policy must define a default route; its absence is a validation error,
 * so it is modelled as optional here.
 *
 * # Examples
 *
 * ```
 * use smista_core::policy::RoutingPolicy;
 *
 * let policy = RoutingPolicy::default();
 * assert!(policy.rules.is_empty());
 * assert!(policy.default.is_none());
 * ```
 */
export type RoutingPolicy = { 
/**
 * Routing rules; evaluated in ascending priority order, first match wins.
 */
rules: Array<RoutingRule>, 
/**
 * Route used when no rule matches.
 */
default: DefaultRoute | null, };
