// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskIntent } from "./TaskIntent.js";

/**
 * Criteria selecting a routing rule.
 */
export type RuleMatch = { 
/**
 * Task type the rule applies to.
 */
task_type: TaskIntent, 
/**
 * Glob of paths the rule applies to, if scoped.
 */
path?: string, };
