// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedPayload } from "./EncryptedPayload.js";

/**
 * A storage record paired with its sealed payload.
 *
 * The router sends these in an `awaiting_decrypt` turn (history to open); the
 * client returns them in the `/continue` bundle after sealing the content of
 * an `awaiting_encrypt` turn. Correlated by `record_id`.
 */
export type SealedRecord = { 
/**
 * Identifier of the storage record the envelope belongs to.
 */
record_id: string, 
/**
 * The sealed envelope.
 */
envelope: EncryptedPayload, };
