// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelUsage } from "./ModelUsage.js";
import type { TaskTypeUsage } from "./TaskTypeUsage.js";
import type { Usage } from "./Usage.js";

/**
 * Response to `GET /sessions/{id}/usage`.
 */
export type SessionUsageResponse = { 
/**
 * Combined usage across the whole session.
 */
total: Usage, 
/**
 * Usage attributed to each model.
 */
by_model: Array<ModelUsage>, 
/**
 * Usage attributed to each task type.
 */
by_task_type: Array<TaskTypeUsage>, };
