// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Full view of a session, returned when it is fetched to be resumed.
 *
 * Carries the session's `messages` and free-form `metadata`. It omits
 * `archived`, since archived sessions are not returned on fetch.
 */
export type SessionDetail = { 
/**
 * Unique session identifier.
 */
id: string, 
/**
 * Human-readable session title.
 */
title: string, 
/**
 * Whether the session's content is end-to-end encrypted.
 */
encrypted: boolean, 
/**
 * When the session was created.
 */
created_at: string, 
/**
 * When the session was last updated.
 */
updated_at: string, 
/**
 * The session's conversation history.
 */
messages: Array<Message>, 
/**
 * Free-form session metadata.
 */
metadata: JsonValue, };
