// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageContent } from "./MessageContent.js";
import type { MessageRole } from "./MessageRole.js";
import type { Provider } from "./Provider.js";

/**
 * One message in a fetched [`SessionDetail`], in clear or sealed.
 *
 * Mirrors [`Message`](crate::message::Message) but carries its `content` as a
 * [`MessageContent`], so an end-to-end encrypted session can return its sealed
 * body without the router ever holding the key. `provider` and `model` name the
 * model that produced an assistant turn and are absent for the other roles.
 */
export type SessionMessageDetail = { 
/**
 * The role of the message's author.
 */
role: MessageRole, 
/**
 * The message content, in clear or sealed.
 */
content: MessageContent, 
/**
 * Provider that produced the message, if applicable.
 */
provider?: Provider, 
/**
 * Model that produced the message, if applicable.
 */
model?: string, };
