// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight view of a session, used in listings and on creation.
 */
export type SessionSummary = { 
/**
 * Unique session identifier.
 */
id: string, 
/**
 * Human-readable session title.
 */
title: string | null, 
/**
 * Opaque scope the session belongs to, if any.
 */
scope?: string, 
/**
 * Whether the session's content is end-to-end encrypted.
 */
encrypted: boolean, 
/**
 * Key fingerprint of the per-session key, if the session is encrypted.
 */
key_id?: string, 
/**
 * When the session was created.
 */
created_at: string, 
/**
 * When the session was last updated.
 */
updated_at: string, 
/**
 * Whether the session is archived.
 */
archived: boolean, };
