// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionMessageDetail } from "./SessionMessageDetail.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Full view of a session, returned when it is fetched to be resumed.
 *
 * Carries the session's `messages` and free-form `metadata`. It omits
 * `archived`, since archived sessions are not returned on fetch.
 */
export type SessionDetail = { 
/**
 * Unique session identifier.
 */
id: string, 
/**
 * Human-readable session title.
 */
title: string, 
/**
 * Opaque scope the session belongs to, if any.
 */
scope?: string, 
/**
 * Key fingerprint of the per-session key, if the session is encrypted.
 */
key_id?: string, 
/**
 * When the session was created.
 */
created_at: string, 
/**
 * When the session was last updated.
 */
updated_at: string, 
/**
 * The session's conversation history.
 */
messages: Array<SessionMessageDetail>, 
/**
 * Free-form session metadata.
 */
metadata: JsonValue, };
