// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageBreakdown } from "./UsageBreakdown.js";

/**
 * Response to `GET /sessions/{id}/usage`.
 */
export type SessionUsageResponse = { 
/**
 * Session the usage belongs to.
 */
session_id: string, 
/**
 * Usage totals and breakdowns.
 */
usage: UsageBreakdown, };
