// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /auth/sign-in`, naming the user to authenticate.
 */
export type SignInRequest = { 
/**
 * Identifier of the user signing in.
 */
user_id: string, };
