// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `POST /auth/sign-in`, carrying the session token.
 *
 * `token` is a secret bearer credential; `expires_at` is when it stops being
 * valid. `Debug` is implemented by hand to redact `token`, so the credential
 * is never leaked through `{:?}` formatting, logs, or traces.
 */
export type SignInResponse = { 
/**
 * Session bearer token. Secret; sent as `Authorization: Bearer`.
 */
token: string, 
/**
 * Instant at which the token expires.
 */
expires_at: string, };
