// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `POST /auth/sign-out`, confirming token revocation.
 */
export type SignOutResponse = { 
/**
 * Whether the session token was revoked.
 */
revoked: boolean, };
