// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable execution profile defined by a `SKILL.md` file.
 *
 * `name` and `description` come from the file's front matter; `instructions`
 * is its Markdown body, which frames the model's behavior for the task.
 */
export type Skill = { 
/**
 * Machine-readable identifier used to resolve the skill by name.
 */
name: string, 
/**
 * Human-readable summary of what the skill does.
 */
description: string, 
/**
 * Behavioral instructions from the skill's Markdown body.
 */
instructions: string, };
