// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable execution profile defined by a `SKILL.md` file.
 *
 * [`name`](Self::name) comes from the file's front matter; [`content`](Self::content)
 * is its Markdown body, which frames the model's behavior for the task. The
 * same type carries a skill whether it was explicitly invoked or merely offered
 * for the model to activate; the two cases differ by where the skill travels in
 * the request, not by shape.
 */
export type Skill = { 
/**
 * Machine-readable identifier used to resolve the skill by name.
 */
name: string, 
/**
 * The `SKILL.md` body: the behavioral instructions for the model.
 */
content: string, };
