// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of a successful `GET /status` response.
 */
export type StatusResponse = { 
/**
 * Service liveness indicator; `"ok"` when the server answers.
 */
status: string, 
/**
 * The running service version.
 */
version: string, };
