// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Usage } from "./Usage.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * A single event in a model's response stream.
 *
 * Serialized with an internally tagged `type` discriminator in snake_case.
 */
export type StreamEvent = { "type": "text_delta", 
/**
 * The text appended by this event.
 */
delta: string, } | { "type": "reasoning_delta", 
/**
 * The reasoning text appended by this event.
 */
delta: string, } | { "type": "tool_call_started", 
/**
 * Identifier correlating this event with its later
 * [`Self::ToolCallRequested`].
 */
call_id: string, 
/**
 * Name of the tool being called.
 */
name: string, } | { "type": "tool_call_requested", 
/**
 * Identifier correlating this call with its later [`Self::ToolResult`].
 */
call_id: string, 
/**
 * Name of the tool to invoke.
 */
name: string, 
/**
 * Arguments for the tool, as a provider-agnostic JSON value.
 */
arguments: JsonValue, } | { "type": "approval_required", 
/**
 * Identifier the approval decision refers to.
 */
approval_id: string, } | { "type": "tool_result", 
/**
 * Identifier matching the originating [`Self::ToolCallRequested`].
 */
call_id: string, 
/**
 * The tool's output.
 */
content: string, 
/**
 * Whether the tool call failed.
 */
is_error: boolean, } | { "type": "usage" } & Usage | { "type": "error", 
/**
 * Machine-readable error code.
 */
code: string, 
/**
 * Human-readable error message.
 */
message: string, } | { "type": "done" };
