// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecision } from "./ApprovalDecision.js";

/**
 * Body of `POST /sessions/{id}/approvals/{approval_id}`.
 */
export type SubmitApprovalRequest = { 
/**
 * The decision being submitted.
 */
decision: ApprovalDecision, 
/**
 * Optional human-readable reason for the decision.
 */
reason?: string, };
