// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecision } from "./ApprovalDecision.js";

/**
 * Response confirming the recorded approval decision.
 */
export type SubmitApprovalResponse = { 
/**
 * Identifier of the approval the decision applies to.
 */
approval_id: string, 
/**
 * The recorded decision.
 */
decision: ApprovalDecision, };
