// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of work a single step of an AI workflow performs.
 *
 * Used by smista-router to match a prompt against the user's routing policy.
 * Each variant serializes to its lowercase name.
 */
export type TaskIntent = "chat" | "plan" | "edit" | "review" | "summarize" | "prompt" | "skill";
