// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelReference } from "./ModelReference.js";
import type { TaskIntent } from "./TaskIntent.js";

/**
 * The user's request: prompt text, optional command and explicit model.
 */
export type TaskInput = { 
/**
 * The prompt text.
 */
text: string, 
/**
 * Explicit task command, overriding intent detection when set.
 */
command?: TaskIntent, 
/**
 * Explicit model to use, bypassing routing when set.
 */
explicit_model?: ModelReference, };
