// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallStatus } from "./ToolCallStatus.js";

/**
 * Payload of a [`TraceEventType::ToolCall`] event.
 *
 * `arguments`, `result` and `error` are recorded as sanitized references, never
 * raw tool input or output.
 */
export type ToolCallPayload = { 
/**
 * Name of the tool that was requested or executed.
 */
tool_name: string, 
/**
 * Lifecycle status of the tool call.
 */
status: ToolCallStatus, 
/**
 * Reference to the tool arguments, if recorded.
 */
arguments?: string, 
/**
 * Reference to the tool result, if recorded.
 */
result?: string, 
/**
 * Reference to the tool error, if the call failed.
 */
error?: string, };
