// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a client-executed tool needs the user's approval first.
 *
 * A tool denied by policy never reaches the client, so `deny` is not a value
 * here.
 */
export type ToolApproval = "allow" | "ask";
