// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecision } from "./ApprovalDecision.js";

/**
 * The result of one client-executed tool, correlated by `call_id`.
 *
 * For an `ask`-mode tool the user's decision rides [`Self::decision`], so the
 * approval and the result arrive together.
 */
export type ToolResult = { 
/**
 * Identifier matching the originating tool request.
 */
call_id: string, 
/**
 * The tool's output.
 */
content: string, 
/**
 * Whether the tool call failed.
 */
is_error: boolean, 
/**
 * The user's decision for an `ask`-mode tool, if one was required.
 */
decision?: ApprovalDecision, };
