// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolApproval } from "./ToolApproval.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * A tool the client must execute on the user's machine.
 */
export type ToolRequest = { 
/**
 * Identifier correlating this call with its later result.
 */
call_id: string, 
/**
 * Name of the tool to invoke.
 */
name: string, 
/**
 * Arguments for the tool, as a provider-agnostic JSON value.
 */
arguments: JsonValue, 
/**
 * Whether the user must approve the call before it runs.
 */
requires_approval: ToolApproval, };
