// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode.js";

/**
 * Tool permissions: the mode required for each named tool.
 *
 * Mirrors the `[tools.permissions]` table, a flat map of tool name to
 * [`PermissionMode`] (e.g. `file_write = "ask"`). A tool with no entry has no
 * explicitly configured mode; callers decide the safe fallback.
 *
 * # Examples
 *
 * ```
 * use smista_core::policy::{PermissionMode, ToolsConfig};
 *
 * let config: ToolsConfig = serde_json::from_value(serde_json::json!({
 *     "permissions": { "file_read": "allow", "shell": "ask", "network": "deny" }
 * }))
 * .unwrap();
 * assert_eq!(config.mode_for("file_read"), Some(PermissionMode::Allow));
 * assert_eq!(config.mode_for("network"), Some(PermissionMode::Deny));
 * assert_eq!(config.mode_for("unlisted"), None);
 * ```
 */
export type ToolsConfig = { 
/**
 * Per-tool permission mode, keyed by tool name.
 */
permissions: { [key in string]: PermissionMode }, };
