// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution status of a tool call.
 *
 * **Provisional**: these variants are a placeholder until the private spec
 * pins the tool-call lifecycle. Serialized as `snake_case`.
 */
export type ToolCallStatus = "pending" | "running" | "completed" | "failed";
