// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedPayload } from "./EncryptedPayload.js";
import type { Payload } from "./Payload.js";

/**
 * A [`TraceEvent`]'s payload, in clear or sealed.
 *
 * A non-encrypted session yields [`Plaintext`](Self::Plaintext) with the typed
 * [`Payload`]. An end-to-end encrypted session yields
 * [`Encrypted`](Self::Encrypted) with the sealed [`EncryptedPayload`] envelope;
 * the router holds no key, so only a client holding the session key can open it
 * into a [`Payload`].
 */
export type TraceEventPayload = { "plaintext": Payload } | { "encrypted": EncryptedPayload };
