// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";
import type { TaskIntent } from "./TaskIntent.js";
import type { TraceEventType } from "./TraceEventType.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * A single recorded execution event within a [`Trace`].
 *
 * Each event carries the routing context of the task that emitted it
 * (`task_type`, `provider`, `model`, `matched_rule`) and a free-form `payload`
 * whose shape depends on `event_type`. The payload is opaque here while the
 * trace vocabulary is still being designed.
 */
export type TraceEvent = { 
/**
 * Kind of trace event.
 */
event_type: TraceEventType, 
/**
 * Detected intent that drove routing for this event's task.
 */
task_type: TaskIntent, 
/**
 * Provider that served the task.
 */
provider: Provider, 
/**
 * Model that served the task.
 */
model: string, 
/**
 * Description of the routing rule that matched, if any.
 */
matched_rule?: string, 
/**
 * When the event occurred.
 */
created_at: string, 
/**
 * Free-form event payload, as an opaque JSON value.
 */
payload: JsonValue, };
