// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trace } from "./Trace.js";

/**
 * Envelope wrapping a [`Trace`] under a `trace` key.
 */
export type TraceResponse = { 
/**
 * The execution trace.
 */
trace: Trace, };
