// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";
import type { TaskIntent } from "./TaskIntent.js";
import type { TraceEventPayload } from "./TraceEventPayload.js";
import type { TraceEventType } from "./TraceEventType.js";

/**
 * A single recorded execution event within a [`Trace`].
 *
 * Each event carries the routing context of the task that emitted it
 * (`task_type`, `provider`, `model`, `matched_rule`) and a typed `payload`
 * whose variant matches `event_type`. For an encrypted session the payload is
 * sealed, so `event_type` still names the kind without opening it.
 */
export type TraceEvent = { 
/**
 * Kind of trace event.
 */
event_type: TraceEventType, 
/**
 * Detected intent that drove routing for this event's task.
 */
task_type: TaskIntent, 
/**
 * Provider that served the task.
 */
provider: Provider, 
/**
 * Model that served the task.
 */
model: string, 
/**
 * Description of the routing rule that matched, if any.
 */
matched_rule?: string, 
/**
 * When the event occurred.
 */
created_at: string, 
/**
 * Typed event payload, in clear or sealed.
 */
payload: TraceEventPayload, };
