// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";
import type { TaskIntent } from "./TaskIntent.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * The recorded outcome of routing and running a single task.
 *
 * `matched_rule` is the human-readable description of the routing rule that
 * selected the model, or `None` when the default route was used. `events`
 * holds the ordered execution events as opaque JSON values.
 */
export type Trace = { 
/**
 * Stable identifier of the trace, for example `trace:xyz`.
 */
id: string, 
/**
 * Session the traced task belongs to.
 */
session_id: string, 
/**
 * Detected intent that drove routing.
 */
task_type: TaskIntent, 
/**
 * Provider that served the task.
 */
provider: Provider, 
/**
 * Model that served the task.
 */
model: string, 
/**
 * Description of the routing rule that matched, if any.
 */
matched_rule?: string, 
/**
 * Ordered execution events, as opaque JSON values.
 */
events: Array<JsonValue>, };
