// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TraceEvent } from "./TraceEvent.js";

/**
 * The recorded outcome of routing and running a session's tasks.
 *
 * `events` holds the session's ordered execution events, oldest first. Each
 * [`TraceEvent`] is self-describing — it carries its own routing context — so
 * the trace needs no top-level routing fields.
 */
export type Trace = { 
/**
 * Session the traced tasks belong to.
 */
session_id: string, 
/**
 * Ordered execution events, oldest first.
 */
events: Array<TraceEvent>, };
