// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a trace event.
 *
 * **Provisional**: these variants are a placeholder until the private spec
 * pins the trace taxonomy. Serialized as `snake_case`.
 */
export type TraceEventType = "message" | "routing_decision" | "context_selection" | "tool_call" | "approval" | "cost";
