// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorBody } from "./ApiErrorBody.js";
import type { CompletedTurn } from "./CompletedTurn.js";
import type { PendingApproval } from "./PendingApproval.js";
import type { PlainRecord } from "./PlainRecord.js";
import type { SealedRecord } from "./SealedRecord.js";
import type { ToolRequest } from "./ToolRequest.js";

/**
 * The outcome of one turn, returned by `/execute` and `/continue`.
 *
 * Internally tagged by `status`. A [`Completed`](Self::Completed) turn carries
 * the assistant message and routing explanation; every other variant is a
 * continuation the client must act on before resuming the run with
 * `/continue`, or a terminal [`Error`](Self::Error).
 */
export type TurnResponse = { "status": "completed" } & CompletedTurn | { "status": "awaiting_tool", 
/**
 * The tool calls the client must run, correlated by `call_id`.
 */
tool_requests: Array<ToolRequest>, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } | { "status": "awaiting_approval", 
/**
 * The decision the client must obtain.
 */
approval: PendingApproval, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } | { "status": "awaiting_decrypt", 
/**
 * Records the client must decrypt, correlated by `record_id`.
 */
records: Array<SealedRecord>, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } | { "status": "awaiting_encrypt", 
/**
 * Records the client must encrypt, correlated by `record_id`.
 */
records: Array<PlainRecord>, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } | { "status": "error", 
/**
 * The structured error body.
 */
error: ApiErrorBody, };
