// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolApproval } from "./ToolApproval.js";
import type { TurnResponse } from "./TurnResponse.js";
import type { Usage } from "./Usage.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * A single event in a streamed turn.
 *
 * Serialized with an internally tagged `type` discriminator in snake_case.
 */
export type TurnEvent = { "type": "text_delta", 
/**
 * The text appended by this event.
 */
delta: string, } | { "type": "reasoning_delta", 
/**
 * The reasoning text appended by this event.
 */
delta: string, } | { "type": "tool_call_started", 
/**
 * Identifier correlating this event with its later
 * [`ToolCallRequested`](Self::ToolCallRequested).
 */
call_id: string, 
/**
 * Name of the tool being called.
 */
name: string, } | { "type": "tool_call_requested", 
/**
 * Identifier correlating this call with its later result.
 */
call_id: string, 
/**
 * Name of the tool to invoke.
 */
name: string, 
/**
 * Arguments for the tool, as a provider-agnostic JSON value.
 */
arguments: JsonValue, 
/**
 * Whether the user must approve the call before it runs.
 */
requires_approval: ToolApproval, } | { "type": "usage" } & Usage | { "type": "turn_end" } & TurnResponse;
