// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorBody } from "./ApiErrorBody.js";
import type { CompletedTurn } from "./CompletedTurn.js";
import type { ContentRef } from "./ContentRef.js";
import type { EncryptedPayload } from "./EncryptedPayload.js";
import type { PendingApproval } from "./PendingApproval.js";
import type { ToolRequest } from "./ToolRequest.js";

/**
 * The outcome of one turn, tagged by `status` with its payload under `data`.
 *
 * Carried by [`TurnResponse`], which adds `allowed_continuations` alongside it.
 */
export type TurnOutcome = { "status": "completed", "data": CompletedTurn } | { "status": "awaiting_tool", "data": { 
/**
 * The tool calls the client must run, correlated by `call_id`.
 */
tool_requests: Array<ToolRequest>, 
/**
 * Router-authored rows to seal (assistant message, tool arguments),
 * keyed by content reference. Empty unless end-to-end encrypted.
 */
to_encrypt?: { [key in ContentRef]?: string }, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } } | { "status": "awaiting_approval", "data": { 
/**
 * The decision the client must obtain.
 */
approval: PendingApproval, 
/**
 * Router-authored rows to seal (for example a plan snapshot), keyed by
 * content reference. Empty unless end-to-end encrypted.
 */
to_encrypt?: { [key in ContentRef]?: string }, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } } | { "status": "awaiting_decrypt", "data": { 
/**
 * Sealed records the client must open, keyed by content reference.
 */
to_decrypt: { [key in ContentRef]?: EncryptedPayload }, 
/**
 * Router-authored rows to seal alongside the decrypt (for example the
 * run-input bundle and the user message sealed at run start), keyed by
 * content reference. Empty unless end-to-end encrypted.
 */
to_encrypt?: { [key in ContentRef]?: string }, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } } | { "status": "awaiting_encrypt", "data": { 
/**
 * Router-authored rows to seal, keyed by content reference.
 */
to_encrypt: { [key in ContentRef]?: string }, 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } } | { "status": "idle", "data": { 
/**
 * Identifier of the recorded trace.
 */
trace_id: string, } } | { "status": "error", "data": { 
/**
 * The structured error body.
 */
error: ApiErrorBody, } };
