// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";
import type { ProviderErrorCategory } from "./ProviderErrorCategory.js";

/**
 * A provider left out of [`ListModelsResponse::models`] because its models
 * could not be listed.
 */
export type UnavailableProvider = { 
/**
 * The provider whose models could not be listed.
 */
provider: Provider, 
/**
 * The classification of the failure that left the provider out.
 */
reason: ProviderErrorCategory, 
/**
 * Human-readable, redacted detail describing the failure, when the
 * provider reported one. Never contains credentials.
 */
message: string | null, };
