// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `PUT /sessions/{id}`, updating title and/or archive state.
 *
 * Each field is optional; omit a field to leave it unchanged.
 */
export type UpdateSessionRequest = { 
/**
 * New title, if changing it.
 */
title?: string, 
/**
 * New archive state, if changing it.
 */
archived?: boolean, };
