// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary.js";

/**
 * Response to `PUT /sessions/{id}`, wrapping the updated session.
 */
export type UpdateSessionResponse = { 
/**
 * The updated session.
 */
session: SessionSummary, };
