// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage and cost metadata for a single model invocation.
 *
 * All fields are optional and omitted from serialization when unset.
 */
export type Usage = { 
/**
 * Tokens in the input/prompt.
 */
input_tokens?: number, 
/**
 * Tokens generated in the output.
 */
output_tokens?: number, 
/**
 * Input tokens served from a provider cache.
 */
cached_tokens?: number, 
/**
 * Tokens spent on reasoning, when reported separately.
 */
reasoning_tokens?: number, 
/**
 * Total tokens, when the provider reports a combined count.
 */
total_tokens?: number, 
/**
 * Cost estimated before the invocation, serialized as a decimal string.
 */
estimated_cost?: string, 
/**
 * Cost reconciled after the invocation, serialized as a decimal string.
 */
actual_cost?: string, 
/**
 * ISO 4217 currency code for the costs; defaults to `USD` when absent.
 */
currency?: string, };
