// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedPayload } from "./EncryptedPayload.js";

/**
 * A message the user typed while the run was working.
 */
export type UserMessage = { 
/**
 * The message text.
 */
text: string, 
/**
 * Sealed form for storage, present only for an end-to-end-encrypted
 * session.
 */
ciphertext?: EncryptedPayload, };
