// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A message the user typed while the run was working.
 */
export type UserMessage = { 
/**
 * The message text.
 */
text: string, };
