// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of the workspace a task runs against.
 */
export type Workspace = { 
/**
 * Absolute path to the workspace root.
 */
root: string, 
/**
 * Current git branch, if the workspace is a git repository.
 */
git_branch?: string, 
/**
 * Current git diff, if any.
 */
git_diff?: string, 
/**
 * Paths the user explicitly referenced.
 */
referenced_paths: Array<string>, 
/**
 * The file the user is actively editing, if any.
 */
active_file?: string, };
